version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        - NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY=${NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY}
        - NEXT_PUBLIC_HUGGINGFACE_API_KEY=${NEXT_PUBLIC_HUGGINGFACE_API_KEY}
        - NEXT_PUBLIC_MINIMAXI_API_KEY=${NEXT_PUBLIC_MINIMAXI_API_KEY}
        - NEXT_PUBLIC_MINIMAXI_GROUP_ID=${NEXT_PUBLIC_MINIMAXI_GROUP_ID}
        - NEXT_PUBLIC_KLING_ACCESS_KEY=${NEXT_PUBLIC_KLING_ACCESS_KEY}
        - NEXT_PUBLIC_KLING_SECRET_KEY=${NEXT_PUBLIC_KLING_SECRET_KEY}
        - NEXT_PUBLIC_KLING_API_URL=${NEXT_PUBLIC_KLING_API_URL}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY=${NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY}
      - NEXT_PUBLIC_HUGGINGFACE_API_KEY=${NEXT_PUBLIC_HUGGINGFACE_API_KEY}
      - NEXT_PUBLIC_MINIMAXI_API_KEY=${NEXT_PUBLIC_MINIMAXI_API_KEY}
      - NEXT_PUBLIC_MINIMAXI_GROUP_ID=${NEXT_PUBLIC_MINIMAXI_GROUP_ID}
      - NEXT_PUBLIC_KLING_ACCESS_KEY=${NEXT_PUBLIC_KLING_ACCESS_KEY}
      - NEXT_PUBLIC_KLING_SECRET_KEY=${NEXT_PUBLIC_KLING_SECRET_KEY}
      - NEXT_PUBLIC_KLING_API_URL=${NEXT_PUBLIC_KLING_API_URL}
    restart: always
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => r.statusCode === 200 ? process.exit(0) : process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - app_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app_network:
    driver: bridge 