apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-maker
  labels:
    app: video-maker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: video-maker
  template:
    metadata:
      labels:
        app: video-maker
    spec:
      containers:
      - name: video-maker
        image: video-maker:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        - name: NEXT_PUBLIC_SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: url
        - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: anon-key
        - name: NEXT_PUBLIC_KLING_API_URL
          valueFrom:
            secretKeyRef:
              name: kling-secrets
              key: api-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20 